---
# THESE ARE THE DEFAULT VARIABLES FOR THE install_maxscale ROLE
vaultsettings: "{{ lookup('hashi_vault', 'secret=secret/lasair/settings', errors='warn') | default('undefined', true) }}"
localsettings: "{{ lookup('template', 'localsettings.yml', errors='warn')|from_yaml | default('undefined', true) }}"
settings: "{% if vaultsettings == 'undefined' %}{{ localsettings }}{% else %}{{ vaultsettings }}{% endif %}"

# Default server names
backend_servers: [ 'backend-db1', 'backend-db2' ]
frontend_servers: [ 'frontend-db1' ]

