---

# Cassandra server
cassandra_server: https://www.apache.org/dist/cassandra
#cassandra_rpm_code: http://rpm.datastax.com/community
cassandra_rpm_code: https://www.apache.org/dist/cassandra/redhat/40x/
cassandra_rpm_gpg_key: https://www.apache.org/dist/cassandra/KEYS
cassandra_cluster_name: 'Lasair4'
cassandra_data_dir: '/var/lib/cassandra'
cassandra_data_dir_nvmessd: '/nvme/16/cassandra'
cassandra_data_dir_satassd: '/ssdraid0/cassandra'
cassandra_data_dir_pcissd: '/nvme0/cassandra'
#cassandra_config_dir: '/tmp'
cassandra_config_dir: '/etc/cassandra'
datacenter: 'somerville'
rack: 'rack1'
