---

# Cassandra server
# 2023-06-21 KWS Abstract out the (dot) version number of cassandra
cassandra_version: 41x
# 2023-06-20 KWS Change of location for the repository
cassandra_server: https://debian.cassandra.apache.org
cassandra_server_keys: https://downloads.apache.org
#cassandra_rpm_code: http://rpm.datastax.com/community
cassandra_rpm_code: https://www.apache.org/dist/cassandra/redhat/{{ cassandra_version }}/
cassandra_rpm_gpg_key: https://www.apache.org/dist/cassandra/KEYS
cassandra_cluster_name: 'Lasair4'
cassandra_data_dir: '/var/lib/cassandra'
cassandra_commitlog_dir: '/var/lib/cassandra'
cassandra_data_dir_nvmessd: '/nvme/16/cassandra'
cassandra_data_dir_satassd: '/ssdraid0/cassandra'
cassandra_data_dir_pcissd: '/nvme0/cassandra'
cassandra_data_dir_bigssdraid: '/nvmeraid/raid0/cassandra'
#cassandra_config_dir: '/tmp'
cassandra_config_dir: '/etc/cassandra'
datacenter: 'somerville'
rack: 'rack1'

replication_factor: 3
keyspace: 'lasair'
