## RUN THIS PLAYBOOK WITH
## > ansible-playbook install-anaconda.yml --ask-vault-pass
---
- hosts: mysqlnodes
  vars:
    vaultsettings: "{{ lookup('hashi_vault', 'secret=secret/lasair/settings', errors='warn') | default('undefined', true) }}"
    localsettings: "{{ lookup('template', 'localsettings.yml', errors='warn')|from_yaml | default('undefined', true) }}"
    settings: "{% if vaultsettings == 'undefined' %}{{ localsettings }}{% else %}{{ vaultsettings }}{% endif %}"
    mysql_root_password: "{{ settings.master_db_root_password }}"
  roles:
    - gkansible.gkservercollection.mariadb

