## RUN THIS PLAYBOOK WITH
## ansible-playbook install-anaconda.yml
---
- hosts: anacondanodes
#  vars:
#    anaconda_parent_dir: /localdisk/scratch/kws
#    anaconda_link_dir: /localdisk/scratch/kws/anaconda
  roles:
    - gkansible.gkservercollection.anaconda

