alerce_password:
alerce_server:
django_secret_key:
fink_servers:
fink_username:
grafana_password:
kafka_password:
kafka_producer:
local_db_password:
local_db_root_password:
master_db_ip:
master_db_password:
master_db_port:
master_db_readonly_password:
master_db_readonly_username:
master_db_root_password:
master_db_username:
powerapi_token:
sherlock_service_ip:
slack_url_urlhook:
