## RUN THIS PLAYBOOK WITH
## > ansible-playbook setup-mariadb-galera.yml
---

# JUST GATHERING FACTS
- hosts: cluster_control,frontend_db1,backend_db1,backend_db2
  become: true

- hosts: cluster_control,frontend_db1,backend_db1,backend_db2
  roles:
    - gkansible.gkservercollection.basic_packages

# MAKE SURE python3-mysqldb IS INSTALLED OR CLUSTERCONTROL FAILS TO INSTALL
- hosts: cluster_control
  become: yes
  tasks:
  - name: "Install python3-mysqldb"
    apt: 
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - python3-mysqldb

- hosts: cluster_control
  become: yes
  roles:
    - role: gkansible.gkservercollection.severalnines_clustercontrol
  vars:
    runtag: "controller"
    vaultsettings: "{{ lookup('hashi_vault', 'secret=secret/lasair/settings', errors='warn') | default('undefined', true) }}"
    localsettings: "{{ lookup('template', 'localsettings.yml', errors='warn')|from_yaml | default('undefined', true) }}"
    settings: "{% if vaultsettings == 'undefined' %}{{ localsettings }}{% else %}{{ vaultsettings }}{% endif %}"

    mysql_root_password: "{{ settings.master_db_root_password }}"
    cmon_mysql_password: "{{ settings.master_db_root_password }}"
    cc_admin:
      - set: true
        email: "k.w.smith@qub.ac.uk"
        password: "{{ settings.master_db_root_password }}"
    cc_license:
      - set: false


# 2022-02-28 KWS Added the following lines to force trigger the passwordless setup
- hosts: backend_db1,backend_db2,frontend_db1
  become: true
  roles:
    - { role: gkansible.gkservercollection.severalnines_clustercontrol, tags: dbnodes }
  vars:
    runtag: "dbnodes"
    clustercontrol_ip_address: "{{ hostvars[groups['cluster_control'][0]]['ansible_all_ipv4_addresses'][0] }}"
    remote_login_user: "root"
    remote_login_user_home: "/root"
    ssh_keyfile: "{{ remote_login_user_home }}/.ssh/id_rsa"
    ssh_user: "{{ remote_login_user }}"


- hosts: cluster_control
  become: yes
  become_user: root
  roles:
    - role: gkansible.gkservercollection.severalnines_clustercontrol
      tags: "deploy-database"
  vars:
    runtag: "deploy-database"
    vaultsettings: "{{ lookup('hashi_vault', 'secret=secret/lasair/settings', errors='warn') | default('undefined', true) }}"
    localsettings: "{{ lookup('template', 'localsettings.yml', errors='warn')|from_yaml | default('undefined', true) }}"
    settings: "{% if vaultsettings == 'undefined' %}{{ localsettings }}{% else %}{{ vaultsettings }}{% endif %}"
    mysql_root_password: "{{ settings.master_db_root_password }}"
    remote_login_user: "root"
    remote_login_user_home: "/root"
    # 2022-02-23 KWS Added clustercontrol_ip_address
    clustercontrol_ip_address: "{{ hostvars[groups['cluster_control'][0]]['ansible_all_ipv4_addresses'][0] }}"

    cc_cluster:
      # minimal create new galera
      - deployment: true
        operation: "create"
        cluster_type: "galera"
        cluster_name: "galera_cluster"
        mysql_cnf_template: "my.cnf.mdb10x-galera"
        mysql_datadir: "/var/lib/mysql"
        mysql_root_password: "{{ settings.master_db_root_password }}"
        mysql_hostnames:
          - "{{ hostvars[groups['backend_db1'][0]]['ansible_all_ipv4_addresses'][0] }}"
          - "{{ hostvars[groups['backend_db2'][0]]['ansible_all_ipv4_addresses'][0] }}"
          - "{{ hostvars[groups['frontend_db1'][0]]['ansible_all_ipv4_addresses'][0] }}"
        mysql_password: "{{ settings.master_db_root_password }}"
        cmon_mysql_password: "{{ settings.master_db_root_password }}"
        mysql_port: 3306
        mysql_version: "10.6"
        ssh_keyfile: "{{ remote_login_user_home }}/.ssh/id_rsa"
        ssh_user: "{{ remote_login_user }}"
        sudo_password: ""
        vendor: "mariadb"
        nodes: 
            - hostname: "{{ hostvars[groups['backend_db1'][0]]['ansible_all_ipv4_addresses'][0] }}"
              hostname_data: "{{ hostvars[groups['backend_db1'][0]]['ansible_all_ipv4_addresses'][0] }}"
              hostname_internal: ""
              port: "3306"
            - hostname: "{{ hostvars[groups['backend_db2'][0]]['ansible_all_ipv4_addresses'][0] }}"
              hostname_data: "{{ hostvars[groups['backend_db2'][0]]['ansible_all_ipv4_addresses'][0] }}"
              hostname_internal: ""
              port: "3306"
            - hostname: "{{ hostvars[groups['frontend_db1'][0]]['ansible_all_ipv4_addresses'][0] }}"
              hostname_data: "{{ hostvars[groups['frontend_db1'][0]]['ansible_all_ipv4_addresses'][0] }}"
              hostname_internal: ""
              port: "3306"


- hosts: backend_db1,backend_db2,frontend_db1
  become: true
  become_user: root
  # 2022-02-14 KWS Added the following role so we can refer to the template implicitly instead of
  #                using an absolute path.
  vars:
    runtag: "credential-templates"
    vaultsettings: "{{ lookup('hashi_vault', 'secret=secret/lasair/settings', errors='warn') | default('undefined', true) }}"
    localsettings: "{{ lookup('template', 'localsettings.yml', errors='warn')|from_yaml | default('undefined', true) }}"
    settings: "{% if vaultsettings == 'undefined' %}{{ localsettings }}{% else %}{{ vaultsettings }}{% endif %}"
    mysql_root_username: root
    mysql_root_password: "{{ settings.master_db_root_password }}"
  roles:
    - gkansible.gkservercollection.severalnines_clustercontrol

