## RUN THIS PLAYBOOK WITH
## > ansible-playbook setup-mariadb-galera-post-install.yml
## Written by claud, reviewed by KWS.
---
- name: Restore standard mariadb.cnf + includedir layout after ClusterControl Galera deploy
  hosts: backend_db1,backend_db2,frontend_db1
  become: true
  roles:
    - gkansible.gkservercollection.post_galera_install_config
