---

dataroot: '/data/mysql/'
tmpdir: '{{ dataroot }}mysqltmp'
datadir: '{{ dataroot }}mysqldata'
logdir: '{{ dataroot }}mysqllog'
defaultdir: '/var/lib/mysql'

mysql_ubuntu_socket: '/var/run/mysqld/mysqld.sock'
mysql_redhat_socket: '{{ defaultdir }}/mysql.sock'

mysql_service_redhat: 'mysqld'
mysql_service_ubuntu: 'mysql'

mysql_port: 3306


sherlock_user: "sherlock"

mysql_databases:
  - name: crossmatch_catalogues
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
 
mysql_users:
  - name: sherlock
    host: "%"
    password: sherlock
    priv: "crossmatch_catalogues.*:ALL"

# Hashicorp Vault information (Used for Lasair deployments). If we have secrets stored there, use them in place of defaults above.
vaultsettings: "{{ lookup('hashi_vault', 'secret=secret/lasair/settings', errors='warn') | default('undefined', true) }}"
localsettings: "{{ lookup('template', 'localsettings.yml', errors='warn')|from_yaml | default('undefined', true) }}"
settings: "{% if vaultsettings == 'undefined' %}{{ localsettings }}{% else %}{{ vaultsettings }}{% endif %}"

mysql_root_password: "{{ settings.local_db_root_password }}"

# Sherlock import type can be "full", "lite" or "empty". If "empty" then only the schema
# structure will be created. No data will be imported, except for any "helper" tables.
sherlock_import_type: "empty"

#sherlock_database_source_dir: '/mnt/cephfs/ken/sherlock_database_files/mysqldata/crossmatch_catalogues'
#sherlock_tables_sql_dir: '/mnt/cephfs/ken/sherlock_innodb_tables'
sherlock_catalogue_data_dir: "{% if sherlock_import_type == 'lite' %}'/mnt/sherlock/data'{% else %}'/mnt/sherlock/data_lite'{% endif %}"
sherlock_sql_dir: "/mnt/sherlock/sql"
