---
# MAIN TASKS TO BE EXECUTED BY install-anaconda ROLE

- name: "Update packages"
  become: true
  apt:
    update_cache: yes # apt-get update
  when: ansible_os_family == "Debian"

- name: install gcc
  apt:
    name: gcc
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: install g++
  apt:
    name: g++
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: install default-libmysqlclient-dev
  apt:
    name: default-libmysqlclient-dev
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: install HTTPS transport (not sure why yet)
  apt:
    name: apt-transport-https
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Insert line in .bashrc file
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: alias anaconda-init='. "$HOME/anaconda/etc/profile.d/conda.sh"'
    state: present
    create: yes

- name: download installer
  get_url:
    url: '{{ anaconda_installer_url }}'
    dest: '/tmp/{{ anaconda_installer_sh }}'
    timeout: '{{ anaconda_timeout_seconds }}'
    checksum: '{{ anaconda_checksum }}'
    mode: 0755

- name: install
  command: 'bash /tmp/{{ anaconda_installer_sh }} -b -p {{ anaconda_install_dir }}'
  args:
    creates: '{{ anaconda_install_dir }}'

- name: delete installer
  file:
    path: /tmp/{{ anaconda_installer_sh }}
    state: absent

- name: update conda pkgs
  when: anaconda_pkg_update
  command: '{{anaconda_link_dir}}/bin/conda update -y --all'

- name: Run commands in conda environment
  shell: '. {{ ansible_env.HOME }}/anaconda/etc/profile.d/conda.sh && conda create -y -n lasair-cassandra python=3.7 pip'

- name: Install swig inside conda environment
  shell:  '. {{ ansible_env.HOME }}/anaconda/etc/profile.d/conda.sh && conda activate lasair-cassandra && conda install -y swig'

- name: Install all the relevant python packages
  shell: '. {{ ansible_env.HOME }}/anaconda/etc/profile.d/conda.sh && conda activate lasair-cassandra && pip install {{ item }}'
  with_items:
    - cassandra-driver
    - mysqlclient
    - docopt
    - pyyaml
    - datetime
    - gkhtm
    - gkutils
    - gkdbutils
