---
# MAIN TASKS TO BE EXECUTED BY install-anaconda ROLE

- name: download installer
  get_url:
    url: '{{ anaconda_installer_url }}'
    dest: '/tmp/{{ anaconda_installer_sh }}'
    timeout: '{{ anaconda_timeout_seconds }}'
    checksum: '{{ anaconda_checksum }}'
    mode: 0755

- name: install
  command: 'bash /tmp/{{ anaconda_installer_sh }} -b -p {{ anaconda_install_dir }}'
  args:
    creates: '{{ anaconda_install_dir }}'

- name: delete installer
  file:
    path: /tmp/{{ anaconda_installer_sh }}
    state: absent

- name: update conda pkgs
  when: anaconda_pkg_update
  command: '{{anaconda_link_dir}}/bin/conda update -y --all'

