---

# 2022-02-07 KWS Test the availability of the credentials

#- name: Check that all the required variables are defined
#  fail: msg="Master db root password is not defined"
#  when: settings.master_db_root_password is not defined

- name: DEBUG - Print the runtag
  debug:
    msg: "runtag = {{ runtag }}"

- include_tasks: deploy-clustercontrol.yml
  when: runtag is defined and runtag == "controller"

# 2025-03-12 KWS At this point cluster control should be installed. We should now
#                remove/comment out any defunct statements from the template config
#                file.
- name: Comment out obsolete line in MariaDB 10.x template file
  ansible.builtin.lineinfile:
    path: /usr/share/cmon/templates/my.cnf.mdb10x-galera
    regexp: '^wsrep_replicate_myisam=1'
    line: '# \g<0>'
    backrefs: yes
  when: runtag is defined and runtag == "controller"

# 2022-02-23 KWS Changed runtag to deploy-database from dbnodes
- include_tasks: setup-passwordless.yml
  when: runtag is defined and runtag == "dbnodes"

# Perform deployment if cc_cluster is defined
- include_tasks: deploy-database.yml
  with_items: "{{ cc_cluster }}"
  when: runtag is defined and runtag == "deploy-database"

# 2022-02-22 KWS Only run this if the runtag is set to credential-templates
- name: Copy .my.cnf file with root password credentials (KWS).
  template:
    src: user-my.cnf.j2
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0600
  when: runtag is defined and runtag == "credential-templates"

