---

dataroot: '/data/mysql/'
tmpdir: '{{ dataroot }}mysqltmp'
datadir: '{{ dataroot }}mysqldata'
logdir: '{{ dataroot }}mysqllog'
defaultdir: '/var/lib/mysql'

# 2021-11-30 KWS Ubuntu 20.04 does NOT have MySQL 5.7. Need to install MySQL 8.0.
mysql_ubuntu_server: 'mysql-server-8.0'
mysql_ubuntu_client: 'mysql-client-8.0'
mysql_ubuntu_client_core: 'mysql-client-core-8.0'
mysql_ubuntu_common: 'mysql-common'
mysql_ubuntu_socket: '/var/run/mysqld/mysqld.sock'

mysql_redhat_repo: 'https://dev.mysql.com/get/mysql80-community-release-el7-6.noarch.rpm'
mysql_redhat_server: 'mysql-community-server'
mysql_redhat_client: 'mysql-community-client'
mysql_redhat_common: 'mysql-community-common'
mysql_redhat_devel: 'mysql-community-devel'
mysql_redhat_libs: 'mysql-community-libs'
mysql_redhat_libs_compat: 'mysql-community-libs-compat'
mysql_redhat_test: 'mysql-community-test'
mysql_redhat_socket: '{{ defaultdir }}/mysql.sock'

mysql_service_redhat: 'mysqld'
mysql_service_ubuntu: 'mysql'

mysql_port: 3306

# Hashicorp Vault information (Used for Lasair deployments). If we have secrets stored there, use them in place of defaults above.
vaultsettings: "{{ lookup('hashi_vault', 'secret=secret/lasair/settings', errors='warn') | default('undefined', true) }}"
localsettings: "{{ lookup('template', 'localsettings.yml', errors='warn')|from_yaml | default('undefined', true) }}"
settings: "{% if vaultsettings == 'undefined' %}{{ localsettings }}{% else %}{{ vaultsettings }}{% endif %}"
mysql_root_password: "{{ settings.local_db_root_password }}"
