---
# THIS PLAYBOOK MUST BE RUN WITH serial = 1. Cassandra nodes must be started one-at-a-time.

# The apt-get service in Ubuntu automatically starts an installed service.
# Shut it down!
#- name: Stop service cassandra, if started
#  service:
#    name: cassandra
#    state: stopped
#  become: true
#  throttle: 1

- name: Stop the other cassandra nodes
  systemd:
    name: cassandra
    state: stopped
    enabled: no
  become: true
  throttle: 1
  when: not ( (play_hosts|length < 5 and inventory_hostname == play_hosts[0]) or (play_hosts|length >= 5 and (inventory_hostname == play_hosts[0] or inventory_hostname == play_hosts[2])) )


- name: Stop the seed nodes
  systemd:
    name: cassandra
    state: stopped
    enabled: no
  throttle: 1
  become: true
  when: (play_hosts|length < 5 and inventory_hostname == play_hosts[0]) or (play_hosts|length >= 5 and (inventory_hostname == play_hosts[0] or inventory_hostname == play_hosts[2]))


- name: Start the seed nodes
  systemd:
    name: cassandra
    state: started
    enabled: yes
  throttle: 1
  become: true
  when: (play_hosts|length < 5 and inventory_hostname == play_hosts[0]) or (play_hosts|length >= 5 and (inventory_hostname == play_hosts[0] or inventory_hostname == play_hosts[2]))


- name: Pause to allow the cassandra seed nodes cassandra to properly start
  wait_for:
    delay: 30
    timeout: 120
    port: 9042
    host: 127.0.0.1
  throttle: 1
  when: (play_hosts|length < 5 and inventory_hostname == play_hosts[0]) or (play_hosts|length >= 5 and (inventory_hostname == play_hosts[0] or inventory_hostname == play_hosts[2]))


- name: Start the other cassandra nodes
  systemd:
    name: cassandra
    state: started
    enabled: yes
  become: true
  throttle: 1
  when: not ( (play_hosts|length < 5 and inventory_hostname == play_hosts[0]) or (play_hosts|length >= 5 and (inventory_hostname == play_hosts[0] or inventory_hostname == play_hosts[2])) )

- name: Pause to allow the cassandra other nodes cassandra to properly start
  wait_for:
    delay: 30
    timeout: 120
    port: 9042
    host: 127.0.0.1
  throttle: 1
  when: not ( (play_hosts|length < 5 and inventory_hostname == play_hosts[0]) or (play_hosts|length >= 5 and (inventory_hostname == play_hosts[0] or inventory_hostname == play_hosts[2])) )

