---

- name: Create database schema script
  template:
    src: crossmatch_catalogues_20220425_schema.sql.j2
    dest: '/tmp/crossmatch_catalogues_20220425_schema.sql'
    mode: 0644
  notify:
    - Recreate views script
    - Recreate helper tables script
    - create databases (in this case, the Sherlock database)
    - create users
    - Run the schema create script
    - Get the Sherlock MyISAM lite datafiles from remote ceph store
    - Copy the lite datafiles
    - Get the Sherlock MyISAM large datafiles from remote ceph store
    - Copy the large datafiles
    - Restart MySQL - so we now recognise the newly copied MyISAM tables.
    - Import the InnoDB data.
    - Import sherlock large table test subset.
    - Run the create helper tables script
    - Run the recreate views script. 

- name: flush handlers
  meta: flush_handlers

