---

- name: Create the ansible_deploy/mariadb directory
  file:
    path: "{{ ansible_env.HOME }}/ansible_deploy/mariadb"
    state: directory
    recurse: yes

# 2024-10-07 KWS Note that we no longer copy "lite" datafiles. We import the
#                sub-20GB database tables from a database dump. Takes longer, but
#                should be more reliable.
- name: Create database schema script
  template:
    src: crossmatch_catalogues_20241002_schema.sql.j2
    dest: '/tmp/crossmatch_catalogues_20241002_schema.sql'
    mode: 0644
  notify:
    - Recreate views script
    - Recreate helper tables script
    - create databases (in this case, the Sherlock database)
    - create users
    - Run the schema create script
    - Import the sub 20GB data tables
    - Get the Sherlock MyISAM large datafiles from remote ceph store
    - Copy the large datafiles
    - Restart MySQL - so we now recognise the newly copied MyISAM tables.
    - Import the InnoDB data.
    - Import sherlock large table test subset.
    - Run the create helper tables script
    - Run the recreate views script. 

- name: flush handlers
  meta: flush_handlers

# 2024-10-07 Sherlock is now updated. Should be no reson to run the updates script.

#- name: Always Import Sherlock updates.
#  mysql_db:
#    name: "crossmatch_catalogues"
#    state: import
#    target: "{{ sherlock_sql_dir }}/sherlock_update_20230926.sql"
#    login_user: "{{ item.name }}"
#    login_password: "{{ item.password | default(omit) }}"
#    login_host: "{{ ansible_all_ipv4_addresses[0] }}"
#  loop: "{{ mysql_users }}"
#  loop_control:
#    label: "{{ item.name }}"
#  when:
#    - mysql_users is defined


