---

- name: Create database schema script
  template:
    src: crossmatch_catalogues_20220425_schema.sql.j2
    dest: '/tmp/crossmatch_catalogues_20220425_schema.sql'
    mode: 0644
  become: true
  notify:
    - Recreate views script
    - Recreate helper tables script
    - create databases (in this case, the Sherlock database)
    - create users
    - Run the schema create script
    - Get the Sherlock MyISAM datafiles from remote ceph store
    - Copy the massive datafiles (over 4.5 TB)
    - Restart MySQL - so we now recognise the newly copied MyISAM tables.
    - Import the InnoDB data.
    - Run the create helper tables script
    - Run the recreate views script. 
    - flush handlers

- name: flush handlers
  meta: flush_handlers
