---
# MAIN TASKS TO BE EXECUTED BY install-anaconda ROLE

- name: Insert anaconda-init line in .bashrc file
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "alias anaconda-init='. \"$HOME/anaconda/etc/profile.d/conda.sh\"'"
    state: present
    create: yes
  notify:
    - download installer
    - install
    - delete installer
    - update conda pkgs

- name: flush handlers
  meta: flush_handlers
