---
# MAIN TASKS TO BE EXECUTED BY install_maxscale ROLE
# xans-install-packages-role
# xans-import-role

# 2022-02-07 KWS Test the availability of the credentials

- name: Check that all the required variables are defined
  fail: msg="Maxscale secret is not defined"
  when: settings.maxscale_secret is not defined

- name: Check if maxscale is installed
  command: dpkg-query -W maxscale
  register: my_package_check_deb
  failed_when: my_package_check_deb.rc > 1
  changed_when: my_package_check_deb.rc == 1

- name: Download maxscale
  get_url: 
    url="{{ maxscale_deb_url }}"
    dest="/tmp/maxscale.deb"
  when: my_package_check_deb.rc == 1

- name: Install maxscale
  apt: deb="/tmp/maxscale.deb"
  become: true
  when: my_package_check_deb.rc == 1

# 2022-02-08 KWS Got rid of the source file. No longer used. Use settings.maxscale_secret instead.
# COPY secrets 
- name: copy secrets to server
  vars:
    dest_key: "/var/lib/maxscale/.secrets"
  copy: 
    content: "{{ settings.maxscale_secret }}" 
    dest: "{{ dest_key }}"
    owner: maxscale
    group: maxscale
    mode: u+r-w,g-rwx,o-rwx


- name: Populate Maxscale template and send to cluster control machine
  template:
    src: maxscale.cnf.j2
    dest: "/etc/maxscale.cnf"
    # owner: bin
    # group: wheel
    # mode: '0644'
  when: runtag is defined and runtag == "credential-templates"
