alter table tcs_cat_glade_v2_3 discard tablespace;
alter table tcs_cat_iras_revised_bright_galaxy_sample_final discard tablespace;
alter table tcs_cat_ppmxl_final discard tablespace;
alter table tcs_helper_trickle_streams discard tablespace;
