---

dataroot: '/data/mysql/'
tmpdir: '{{ dataroot }}mysqltmp'
datadir: '{{ dataroot }}mysqldata'
logdir: '{{ dataroot }}mysqllog'
defaultdir: '/var/lib/mysql'

mysql_ubuntu_server: 'mysql-server-5.7'
mysql_ubuntu_client: 'mysql-client-5.7'
mysql_ubuntu_client_core: 'mysql-client-core-5.7'
mysql_ubuntu_common: 'mysql-common'
mysql_ubuntu_socket: '/var/run/mysqld/mysqld.sock'

mysql_redhat_repo: 'https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm'
mysql_redhat_server: 'mysql-community-server'
mysql_redhat_client: 'mysql-community-client'
mysql_redhat_common: 'mysql-community-common'
mysql_redhat_devel: 'mysql-community-devel'
mysql_redhat_libs: 'mysql-community-libs'
mysql_redhat_libs_compat: 'mysql-community-libs-compat'
mysql_redhat_test: 'mysql-community-test'
mysql_redhat_socket: '{{ defaultdir }}/mysql.sock'

mysql_service_redhat: 'mysqld'
mysql_service_ubuntu: 'mysql'

mysql_root_password: 'OPV537'
#mysql_root_password: 'root123password'

mysql_port: 3306

