---
# This hander will be executed as soon as the create_keyspace.cql CQL file is created.

- name: Create candidates CQL file
  template:
    src: candidates.cql.j2
    dest: '/tmp/candidates.cql'
    mode: 0644

- name: Create noncandidates CQL file
  template:
    src: noncandidates.cql.j2
    dest: '/tmp/noncandidates.cql'
    mode: 0644

- name: Create htmcandidates CQL file
  template:
    src: htmcandidates.cql.j2
    dest: '/tmp/htmcandidates.cql'
    mode: 0644

- name: Create keyspace and tables
  command: "{{ item }}"
  with_items:
    - 'cqlsh -f /tmp/create_keyspace.cql'
    - 'cqlsh -f /tmp/candidates.cql'
    - 'cqlsh -f /tmp/noncandidates.cql'
    - 'cqlsh -f /tmp/htmcandidates.cql'

# 2022-04-11 KWS Removed the line which deletes /tmp/create_keyspace.cql. Allows this script to become idempotent.
- name: delete cql files
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '/tmp/candidates.cql'
    - '/tmp/noncandidates.cql'
    - '/tmp/htmcandidates.cql'
