---
# MAIN TASKS TO BE EXECUTED BY install-anaconda ROLE

- name: Update packages
  become: true
  apt:
    update_cache: yes # apt-get update
  when: ansible_os_family == "Debian"

- name: install Open JDK 11 Debian
  apt:
    name: openjdk-11-jdk
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: install cURL Debian
  apt:
    name: curl
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: install cURL RedHat
  yum:
    name: curl
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: install Open JDK 11 CentOS
  yum:
    name: java-11-openjdk
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: main configuration (cassandra.repo)
  template:
    src: cassandra.yum.repo.j2
    dest: '/etc/yum.repos.d/cassandra.repo'
    mode: 0644
    owner: root
    group: root
  become: true
  when: ansible_os_family == "RedHat"

- name: install HTTPS transport (not sure why yet)
  apt:
    name: apt-transport-https
    state: present
  become: true
  when: ansible_os_family == "Debian"

# 2023-06-20 KWS Minor update to this. Add key via curl not wget.
- name: get cassandra repo
  shell: 'curl {{ cassandra_server_keys }}/cassandra/KEYS | sudo apt-key add -'
  become: true
  when: ansible_os_family == "Debian"

- name: add cassandra
  shell: 'echo "deb {{ cassandra_server }} {{ cassandra_version }} main" > /etc/apt/sources.list.d/cassandra.sources.list'
  become: true
  when: ansible_os_family == "Debian"

- name: Update packages now cassandra repo added
  become: true
  apt:
    update_cache: yes # apt-get update
  when: ansible_os_family == "Debian"

- name: install Cassandra on Debian systems
  apt:
    name: cassandra
    state: present
  become: true
  when: ansible_os_family == "Debian"
  notify:
    - Stop service cassandra, if started
    - Remove old Cassandra data
    - Create the new Cassandra data
    - main configuration (cassandra.yaml)
    - Check for cassandra_mapping.txt
    - Abort if the mapping file is missing
    - Load mapping file into cassandra_map
    - Gather any entries matching this host
    - Abort if this host is not in the mapping file
    - Set rack from the mapping
    - main configuration (cassandra-rackdc.properties)
    - Create the prometheus directory
    - Download the prometheus agent
    - Prometheus agent configuration file
    - Add the prometheus agent to the cassandra environment

#    - Start the seed nodes
#    - Pause to allow the cassandra seed nodes cassandra to properly start
#    - Start the other cassandra nodes
#    - Pause to allow the cassandra other nodes cassandra to properly start


- name: install Cassandra on RedHat systems
  yum:
    name: cassandra
    state: present
  become: true
  when: ansible_os_family == "RedHat"
  notify:
    - Stop service cassandra, if started
    - Remove old Cassandra data
    - Create the new Cassandra data
    - main configuration (cassandra.yaml)
    - Check for cassandra_mapping.txt
    - Abort if the mapping file is missing
    - Load mapping file into cassandra_map
    - Gather any entries matching this host
    - Abort if this host is not in the mapping file
    - Set rack from the mapping
    - main configuration (cassandra-rackdc.properties)
    - Create the prometheus directory
    - Download the prometheus agent
    - Prometheus agent configuration file
    - Add the prometheus agent to the cassandra environment
#    - Start the seed nodes
#    - Pause to allow the cassandra seed nodes cassandra to properly start
#    - Start the other cassandra nodes
#    - Pause to allow the cassandra other nodes cassandra to properly start


- name: flush handlers
  meta: flush_handlers
