---

# 2022-02-07 KWS Test the availability of the credentials

- name: Check that all the required variables are defined
  fail: msg="Local root password is not defined"
  when: settings.local_db_root_password is not defined

# 2021-06-14 KWS Change swappiness from default 60 to 10.
- name: set swapiness
  sysctl:
    name: vm.swappiness
    value: "10"
  become: true

#- name: Update packages
#  become: true
#  apt:
#    update_cache: yes # apt-get update
#  when: ansible_os_family == "Debian"

- name: Use the command apt-get update instead of the apt module
  command: apt-get update
  become: true
  when: ansible_os_family == "Debian"

# For RedHat - need to get the Yum repos, then install.

- name: Install Oracle MySQL yum repository RedHat Family.
  yum:
    name: "{{ mysql_redhat_repo }}"
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: Install Oracle MySQL for RedHat Family.
  yum:
    name: 
      - "{{ mysql_redhat_server }}"
      - "{{ mysql_redhat_client }}"
      - "{{ mysql_redhat_common }}"
      - "{{ mysql_redhat_devel }}"
      - "{{ mysql_redhat_libs }}"
      - "{{ mysql_redhat_libs_compat }}"
      - "{{ mysql_redhat_test }}"
    state: present
  become: true
  when: ansible_os_family == "RedHat"
  notify:
    - Pause to allow MySQL to build its tablespaces
    - Stop service mysql, if started
    - Create the mysql data directory
    - Create the mysql tmp directory
    - Create the mysql log directory
    - Move the default installation file to new directory 
    - Recreate the old mysql directories
    - mysql configuration file (my.cnf)
    - apparmor configuration file (alias)
    - Restart apparmor
    - start and enable mysql
    - Set the root password
    - Secure the root user for IPV6 localhost (::1)
    - Secure the root user for IPV4 localhost (127.0.0.1)
    - Secure the root user for localhost domain
    - Secure the root user for server_hostname domain
    - Deletes anonymous server user

- name: Install Oracle MySQL server for Debian.
  apt:
    name: 
      - "{{ mysql_ubuntu_server }}"
      - "{{ mysql_ubuntu_client }}"
      - "{{ mysql_ubuntu_client_core }}"
      - "{{ mysql_ubuntu_common }}"
      # Install python3-mysqldb in the default setup on the client - so we can do root password config
      - python3-mysqldb
    state: present
  become: true
  when: ansible_os_family == "Debian"
  notify:
    - Pause to allow MySQL to build its tablespaces
    - Stop service mysql, if started
    - Create the mysql data directory
    - Create the mysql tmp directory
    - Create the mysql log directory
    - Move the default installation file to new directory 
    - Recreate the old mysql directories
    - mysql configuration file (my.cnf)
    - apparmor configuration file (alias)
    - Restart apparmor
    - start and enable mysql
    - Set the root password
    - Secure the root user for IPV6 localhost (::1)
    - Secure the root user for IPV4 localhost (127.0.0.1)
    - Secure the root user for localhost domain
    - Secure the root user for server_hostname domain
    - Deletes anonymous server user
    - Removes the test database

- name: flush handlers
  meta: flush_handlers
